CREATE DATABASE Kino1;
USE Kino1;
CREATE TABLE Klient (Id_Klient INT PRIMARY KEY AUTO_INCREMENT , Imie VARCHAR(20),Nazwisko VARCHAR(20)) ;
CREATE TABLE Sala (Id_Sala INT AUTO_INCREMENT PRIMARY KEY, Nr_Sali INT) ;
CREATE TABLE Film (Id_Film INT AUTO_INCREMENT PRIMARY KEY,Tytuł VARCHAR(45),Reżyser VARCHAR(20), CzasTrwania_minut INT, RokProdukcji INT) ;
CREATE TABLE Seans (Id_Seans INT AUTO_INCREMENT PRIMARY KEY,Data DATE,Godzina TIME, Id_Sala INT, Id_Film INT, FOREIGN KEY (Id_Sala)  REFERENCES Sala (Id_Sala), FOREIGN KEY (Id_Film)  REFERENCES Film (Id_Film)) ;
CREATE TABLE Bilet (Id_Bilet INT AUTO_INCREMENT PRIMARY KEY, Id_Klient INT, Id_Seans INT, FOREIGN KEY (Id_Klient)  REFERENCES Klient (Id_Klient), FOREIGN KEY (Id_Seans)  REFERENCES Seans (Id_Seans)) ;